### ISSUE TITLE
Use class names instead of instance names

### ISSUE THREAD

**Issue by chky-nmnsoftware** [pixijs/devtools#35]
Hello there. Just like the title says, I believe it would be better to use the actual class names instead of instance names and instead replace the type property with the instance property.

Currently, it is difficult to navigate around because everything is `Container` or `Sprite`, and I can only check the name of the class by clicking on it. Instead, it would be nice to keep the icons for instances (so all containers share the same icons, all sprites, etc), but use the class names for the main navigator instead (so instead of `Container; Container`, it would use whatever class name, so `Header, Footer`, assuming that both the class `Header` and the class `Footer` extend `Container`) and under the `type` property, just specify what type of PIXI instance it extends (in our case, it would be `Container`). This would make it so much easier to navigate.

**Comment by Zyie** [comment]
Hey @chky-nmnsoftware thanks for the suggestion, I think this is a good idea and i will implement ASAP

**Comment by Zyie** [comment]
this has been added in 2.0.0 which will land in a couple of days after it passing the review
